### ISSUE TITLE
gpg pinentry (macos)

### ISSUE THREAD

**Issue by molleweide** [bevry/dorothy#109]
For what it seems gpg with pinentry is not working properly for me on
macOS. Personally, I have read through the `setup-git` command and feel like
I understand it fyi. But I have to read through it a couple more times
to really feel like I understand everything.

I searched for neovim pinentry and found this plugin issue. Maybe it
will reveal some interesting information:

## resources
https://github.com/jamessan/vim-gnupg/issues/32
https://github.com/jamessan/vim-gnupg
https://gist.github.com/troyfontaine/18c9146295168ee9ca2b30c00bd1b41e

**Comment by molleweide** [comment]
I believe that the problem could be that this is what shows in agent conf on
my intel after we ran `setup-git` together yesterday:

`pinentry-program /usr/local/bin/pinentry`

Does it say pinentry-mac on your machine?

**Comment by molleweide** [comment]
using pinentry-mac on cli did the trick.

next: test inside of neovim.

**Comment by molleweide** [comment]
it did not work in neovim. I shall install the plugin, test and report back.
I will create a pr to add pinentry-mac if i get it to work.

**Comment by molleweide** [comment]
There is an export variable called `GPG_TTY` that this thread mentions you should export https://gist.github.com/troyfontaine/18c9146295168ee9ca2b30c00bd1b41e#step-4-modify-your-shell

**Comment by balupton** [comment]
It should be inside the ssh source files, perhaps I forgot to commit it, will look tomorrow

**Comment by molleweide** [comment]
Ok, or maybe I made a mistake when searching

**Comment by balupton** [comment]
Is it not set for you?

https://github.com/bevry/dorothy/blob/47b79d02340870f494991563037f79fc9641edd8/sources/ssh.sh#L8-L19

**Comment by molleweide** [comment]
Yo! It is set! I was searching on the wrong computer.

**Comment by balupton** [comment]
So all good, was the pinentry to pinentry-mac change still needed?

**Comment by molleweide** [comment]
At the moment, I am not sure. It was necessary yesterday when I did the testing but I will have to do some more test rounds.

**Comment by balupton** [comment]
Ok cool, keep me posted, hope you feel better

**Comment by molleweide** [comment]
gpg seems to work and the neovim issue is unrelated so I'll close. But I think we should add a check
for darwin and use `pinentry-mac` instead. It seems to be more approriate, or what do you think?

**Comment by balupton** [comment]
> gpg seems to work and the neovim issue is unrelated so I'll close. But I think we should add a check
> for darwin and use `pinentry-mac` instead. It seems to be more approriate, or what do you think?

I'll review later today.

**Comment by molleweide** [comment]
How often is one expected to have to supply the gpg passw after having ran the `setup-git` script? Do you know this?
I am not sure what pattern is atm.

**Comment by molleweide** [comment]
it turns out that editing encrypted files works with neovim with the current configuration and pinentry-mac and the issue seems to be with the `neogit` plugin. I have filed  a started the process of filing a report to `neogit`.
