### ISSUE TITLE
Installation not working because of dependency on `choose-option`

### ISSUE THREAD

**Issue by reisub0** [bevry/dorothy#120]
I don't know if I'm doing something wrong but the instructions both for trying out dorothy and for installing it seems to depend on `choose-option` (which obviously does not exist without dorothy installed)

```
 !  ~  bash -ic "$(curl -fsSL https://dorothy.bevry.workers.dev/commands/what-is-my-ip)"                                                                                       3021ms  Mon Mar 28 16:46:54 2022
bash: choose-option: command not found

!  ~  bash -ilc "$(curl -fsSL https://raw.githubusercontent.com/bevry/dorothy/master/commands/dorothy)"                                                                        281ms  Mon Mar 28 16:48:29 2022
bash: choose-option: command not found
```

Platform details (I don't think it is relevant): Tried on macOS w/ Apple Silicon 12.3 with fish and bash.

**Comment by balupton** [comment]
Thanks, I reproduced this a while back. It'll get fixed end of this week. Sorry for the inconvenience, Dorothy is undergoing a lot of improvements right now in prep for its public launch on April 12th.

**Comment by balupton** [comment]
This issue is now resolved.
