### ISSUE TITLE
Bug: installs on fresh macOS (no homebrew) fail

### ISSUE THREAD

**Issue by selfagency** [bevry/dorothy#166]
```sh
❯ bash -ilc "$(curl -fsSL https://dorothy.bevry.me/install)"
bash: fs-realpath: command not found
```

**Comment by balupton** [comment]
will look into it now

**Comment by balupton** [comment]
try now

**Comment by balupton** [comment]
actually wait a moment

**Comment by balupton** [comment]
ok should be properly fixed now

**Comment by balupton** [comment]
actually, perhaps best to come back tomorrow - I've found  away to automate testing on fresh macos environment, and the testing is failing.

**Comment by balupton** [comment]
Okay, install on fresh macos is now working again, and testing has been implemented to guarantee it working. Thank you so much for reporting this.

**Comment by balupton** [comment]
Just fixed another bug affecting fresh macos, and the tests for it are now passing and comprehensive.

**Comment by selfagency** [comment]
Unfortunately...

```sh
kingpin on  main [!] is 󰏗 v0.1.0 via  v20.6.0 took 2s 
❯ bash -ilc "$(curl -fsSL https://dorothy.bevry.me/install)"                                                                                                                                                       10:22:30 PM
bash: #!/usr/bin/env: No such file or directory

kingpin on  main [!] is 󰏗 v0.1.0 via  v20.6.0 
❯                                                                                                                                                                                                        ❌127     10:22:31 PM

kingpin on  main [!] is 󰏗 v0.1.0 via  v20.6.0 
❯ curl -fsSL https://dorothy.bevry.me/install | bash                                                                                                                                                               10:22:40 PM
┌  Updating the Dorothy installation at /Users/daniel/.local/share/dorothy  ┐
Menu timed out [60].
failure
...Dorothy was unable to be updated, you will have to figure this out now.
```

**Comment by balupton** [comment]
Which version of macos is this, and which architecture? I'll see if I can reproduce manually via a virtual machine.

**Comment by balupton** [comment]
Haven't had time to test manually, however I've pushed new updates and new install instructions that might fix this.

The only remaining todo related to improving the install flow is: https://github.com/bevry/dorothy/issues/164

**Comment by balupton** [comment]
Okay, I've pushed up all the refactoring I can think of that would impact this. I've also completed all code changes related to stability of Dorothy.

As such, please try removing the broken installation:

``` bash
rm -rf '/Users/daniel/.local/share/dorothy'
```

Then going through the setup again:
https://github.com/bevry/dorothy#setup

Please let me know if there is still a problem, and I'll attend to it. Thanks for your patience!
