### ISSUE TITLE
Bug: File not found: ../themes/trial.nu

### ISSUE THREAD

**Issue by jondpenton** [bevry/dorothy#176]
I tried to install and use dorothy with Nu, but ran into an error:

<img width="609" alt="image" src="https://github.com/bevry/dorothy/assets/3173124/04e9acff-4af5-4b86-b73b-332d4b5d493e">

Once the trial else if is removed, Nu starts up with no errors.

**Comment by balupton** [comment]
Sorry about that, should be fixed now. Let me know if not.
