### ISSUE TITLE
promote @balupton's `restore`

### ISSUE THREAD

**Issue by balupton** [bevry/dorothy#18]
Once dorothy is cloned via `setup-dorothy`, it may be beneficial to ask the user if they wish to restore some essentials from another machine.

I'm currently achieving this via:

https://github.com/balupton/dotfiles/blob/cd3bf7b850a572f69a0da22ed7c1500ee81891c5/commands/restore

**Comment by molleweide** [comment]
yeah i'm definitely going to look into this.

**Comment by balupton** [comment]
Plan will be to put it inside setup-dorothy after dorothy's clone but before the user repo clone. With a prompt of which directories you wish to restore; perhaps with a configuration array so the user can add/change which directories are prompted.

That said, the fact it needs rsync, or scp, to be useful defeats the purpose of having it so early in the setup cycle. As things like homebrew will need to be configured first.

Perhaps it really is best left a user shareable command, rather than a dorothy promotion. Or perhaps just a guide in the tips section of the discussion forum.

**Comment by balupton** [comment]
This is best served by documentation, around the `cpr` command, or around encryption `*.local` directories.
