### ISSUE TITLE
Suggestion: consider using `brew shellenv`

### ISSUE THREAD

**Issue by Coridyn** [bevry/dorothy#189]
eval "$(/opt/homebrew/bin/brew shellenv)"

**Comment by balupton** [comment]
For me, this is what it outputs:

```
> brew shellenv
export HOMEBREW_PREFIX="/usr/local";
export HOMEBREW_CELLAR="/usr/local/Cellar";
export HOMEBREW_REPOSITORY="/usr/local/Homebrew";
export PATH="/usr/local/bin:/usr/local/sbin${PATH+:$PATH}";
[ -z "${MANPATH-}" ] || export MANPATH=":${MANPATH#:}";
export INFOPATH="/usr/local/share/info:${INFOPATH:-}";
```

There isn't anything there that Dorothy doesn't already support, so I'm going to close this. If it starts outputting things that Dorothy itself doesn't already detect, then we can reevaluate.
