### ISSUE TITLE
Support: experience of nushell on WSL2

### ISSUE THREAD

**Issue by wasdee** [bevry/dorothy#197]
ref #196 

for below issue, we might consider add docs, tell user what to do after or handle with automatic script

## setup and context
- WSL2 latest
- install nushell via homebrew latest initially, set as login shell
- install dorothy via `bash -ic "$(curl -fsSL https://dorothy.bevry.me/install)"`
- my username is `nam`, home directory at `/home/nam`

## Issue found
1. dorothy not working since [nu config]/login.nu is not source
2. carapace not found
3. it shoud say how to remove sponsor msg, once in a while is acceptable.

#### reproduce
1. freshy install nushell 
2. install dorothy
4. `$env.DOROTHY` not work

#### quick fix 
append to  [nu config]/config.nu
```
const env_path = ($nu.env-path | path dirname | path join login.nu)
source $env_path
```

#### reproduce
use MS terminal -> Ubuntu

> Not found when use terminal via VSCode 

#### error msg
```nu
Error: nu::shell::external_command

  × External command failed
    ╭─[/home/nam/.local/share/dorothy/sources/autocomplete.nu:10:1]
 10 │         # init script is placeholder, so replace it
 11 │         carapace _carapace nushell  | save --force ~/.local/state/carapace/init.nu
    ·         ────┬───
    ·             ╰── executable was not found
 12 │     }
    ╰────
  help: No such file or directory (os error 2)

Error: nu::shell::external_command

  × External command failed
    ╭─[/home/nam/.local/share/dorothy/sources/autocomplete.nu:10:1]
 10 │         # init script is placeholder, so replace it
 11 │         carapace _carapace nushell  | save --force ~/.local/state/carapace/init.nu
    ·         ────┬───
    ·             ╰── executable was not found
 12 │     }
    ╰────
  help: No such file or directory (os error 2)
```

#### workaround
run `setup-util-carapace` 
after this, once it shows `open /home/nam/.config/carapace/specs: no such file or directory` after another shell login terminal

**Comment by balupton** [comment]
> * carapace not found

Definitely a bug. Fortunately the fix for #196 will also allow a better fix for this too. I'll queue up when I resume work.

> `open /home/nam/.config/carapace/specs: no such file or directory`

Not sure what is happening there. Did it resolve?

> ### dorothy not working since [nu config]/login.nu is not source

That's strange... during the install process (can be run again via `dorothy install`) did it configure itself for nushell? As it should insject `source '$DOROTHY/init.nu' # Dorothy` into $nu.loginshell-path`. `$DOROTHY` is evaluated before it is written.

https://github.com/bevry/dorothy/blob/a0c26372296165db3947210e606bd7e0bcea5795/commands/dorothy#L1255-L1257

> 3\. it shoud say how to remove sponsor msg, once in a while is acceptable.

How often would say is once in a while?

**Comment by wasdee** [comment]
> > `open /home/nam/.config/carapace/specs: no such file or directory`
> 
> Not sure what is happening there. Did it resolve?
this one might be it is creating the `specs` file after the fact. and sequential run it disappear

**Comment by wasdee** [comment]
> > 3. it shoud say how to remove sponsor msg, once in a while is acceptable.
> 
> How often would say is once in a while?

how about once a day?

**Comment by wasdee** [comment]
> > ### dorothy not working since [nu config]/login.nu is not source
> 
> That's strange... during the install process (can be run again via `dorothy install`) did it configure itself for nushell? As it should inject `source '$DOROTHY/init.nu' # Dorothy` into `$nu.loginshell-path`. `$DOROTHY` is evaluated before it is written.
> 
> https://github.com/bevry/dorothy/blob/a0c26372296165db3947210e606bd7e0bcea5795/commands/dorothy#L1255-L1257

I double check [ `login.nu` the nu's docs](https://www.nushell.sh/book/configuration.html#configuration-with-login-nu) 
things work perfectly with the right parameter when run it e.g. `nu -l -i` 

I missed this in both vscode and ms terminal. so, it appears that my nushell is not sourcing dorothy. 🥲 sorry 

```json
"terminal.integrated.profiles.linux": {
		
		"bash": {
			"path": "bash",
			"icon": "terminal-bash"
		},
		"zsh": {
			"path": "zsh"
		},
		"fish": {
			"path": "fish"
		},
		"tmux": {
			"path": "tmux",
			"icon": "terminal-tmux"
		},
		"NuShell": {
            "path": "/home/linuxbrew/.linuxbrew/bin/nu",
            "args": ["--login", "-i"],
			"icon": "fold"
        },
		"pwsh": {
			"path": "pwsh",
			"icon": "terminal-powershell"
		}
	},
```

**Comment by balupton** [comment]
Can you send a PR to add VSCode instructions to https://github.com/bevry/dorothy/blob/master/docs/dorothy/dorothy-not-loading.md

**Comment by wasdee** [comment]
https://github.com/bevry/dorothy/pull/200

**Comment by balupton** [comment]
merged with some changes :-)

also, now there is a chance that you will be in the shoutout, as you are now a contributor! 🚀 I wonder if you'll feel differently about its frequency now? 😉

**Comment by balupton** [comment]
So what is left of this is the carapace fix. I did look through the code a few days ago and couldn't determine what could have caused the failure. However I'll try to freshly reproduce.

**Comment by wasdee** [comment]
> merged yours PRs with some changes :-)
> 
> also, now there is a chance that you will be in the shoutout, as you are now a contributor! 🚀 I wonder if you'll feel differently about its frequency now? 😉

Thank you 😊, as you see fit.  This project is awesome. I just can't help myself to contribute. 🤣
