### ISSUE TITLE
docs give me unclear what to do after install

### ISSUE THREAD

**Issue by wasdee** [bevry/dorothy#198]
# context
- I read the `README.md`
  - I watched the video.
  - I saw nu shell user dotfiles
- I use `chezmoi` and keep my dotfiles on github.
- I use with `mise`(prev rtx ,rust cli replacement for asdf)

# problem
i don't know how to customize this for my own use.
- i can cherry-pick some configs that is useful to me to my dotfiles but that would be missing out update to these amazing scripts, should i update manually?
- forking this repo, and keep rebasing?
- I faced a few issues on #197. im not sure which `setup-` scripts should i run minimum to get smooth start. 

# sugesstion
maybe we could have a clear recommended way in the docs how to use this ideally.

**Comment by wasdee** [comment]
oh i see. i should add user directory to github dotfiles

**Comment by balupton** [comment]
> oh i see. i should add user directory to github dotfiles

Yeah, unfortunately the mkdirp workaround at #196 would have probably caused the install process to assume you already have your user configuration preconfigured, so you likely didn't get a user configuration setup flow that asked you about how you want to go about your user config and what it's for.

In short, your user configuration goes in $DOROTHY/user which is a symlink to a user configuration directory, this houses your commands and configuration, with support for local commands and config (which by default are gitignored, however both myself and @molleweide choose to commit and encrypt them instead).

The user configuration allows you to write your own commands and override dorothy commands, as well as specify configuration for dorothy. You can copy and paste commands/config from other users into yours. If multiple people start finding commands useful, they can go into the dorothy core.

---

> * I watched the video.

I gave an updated presentation at CampJS November 2023 however they are having some delays with the upload.

Here was the agenda for the presentation:

Dorothy Talk

Chapter 1
- [ ] Observed an undercurrent where new machines has caused inconveniences, delays, and bugs
    - [ ] From the complexity of setting up an entire ecosystem correctly like node, python, rust, ruby, go,
    - [ ] To installing the correct packages for correct versions for correct platforms
    - [ ] To configuring the machines
    - [ ] To learning how to use the differences across machines
- [ ] These are all problems I know well, and Dorothy has incrementally evolved over 10 years to solve all these problems
    - [ ] My machines no matter the platform or architecture are installed and configured consistently and easily
    - [ ] The dev tooling such as compilers and env variables are configured correctly for the machines capabilities 
    - [ ] When using the machines, I have commands and configuration that work on all of them, making my life easier
    - [ ] When writing commands, I can leverage a core of hundreds of commands to make my life way easier

Chapter 2
- [ ] What is a terminal
- [ ] What is a shell
- [ ] What is bash and zsh and so on
- [ ] What are dotfiles
- [ ] How do dotfiles evolve
- [ ] What did dorothy solve
- [ ] How has dorothy evolved
- [ ] Who uses dorothy and why

Chapter 3
- [ ] What can we do with dorothy
- [ ] select-shell
        - [ ] cross-shell support
- [ ] dorothy theme
    - [ ] cross-shell theming
- [ ] setup-system [install|update]
    - [ ] system
    - [ ] ecosystems
    - [ ] cleanup
- [ ] setup-utils
- [ ] setup-dns
    - [ ] Encrypted DNS
    - [ ] tunnels 
- [ ] setup-git
- [ ] ssh-helper
- [ ] edit (command and preferences)
    - [ ] SSH detection
- [ ] until-success
- [ ] secret
- [x] mount-helper
- [x] btrfs-helper
- [x] service-helper
- [x] setup-server
- [x] ytd-helper
- [x] macos-drive
- [x] macos-installer
- [x] checksum
- [x] cpr
- [ ] Other things in showcase docs

Chapter 5
- [ ] So how does it work?
- [ ] Shell dotfiles extended
- [ ] Dorothy init script
- [ ] Dorothy env script 
- [ ] Dorothy interactive script
- [ ] Dorothy user repository
- [ ] Dorothy structure
- [ ] Dorothy approach to promotion
- [ ] 


Chapter 4
- [ ] Helps us write our own commands
- [ ] Styling Prompt Demo (echo-rainbow)
    - [ ] Ask for an input to style
    - [ ] Bash.bash failure 
    - [ ] Choose for style
        - [ ] Paging
        - [ ] Resizing 
        - [ ] Hints
    - [ ] Confirm for blink
    - [ ] Get theme (different notice styles)
    - [ ] Lowercase and other transforms
    - [ ] Conventions for help and args and tests
        - [ ] Multiple color args
- [ ] Ask, choose, confirm
- [ ] Echo style
- [ ] Echo transforms
- [ ] Eval helper
- [ ] Echo clear line
- [ ] Ttyx
- [ ] Debug Bash
- [ ] Eval tester
- [ ] Config helper
- [ ] Service helper
- [ ] Command exists
- [ ] Setup utils
- [ ] get-installer
- [ ] Sources
- [ ] "is" commands
- [ ] Get commands
- [ ] Waiter

Chapter 6
- [ ] Getting our hands dirty
- [ ] Platform support
- [ ] dorothy repl
- [ ] Writing a utility installer
    - [ ] setup-util
- [ ] Writing a echo transformer
    - [ ] on_input
- [ ] Writing a generic commsnd
    - [ ] Argument passing

**Comment by wasdee** [comment]
> rothy Talk
> 
> Chapter 1

look forward for your upcoming video 😊
