### ISSUE TITLE
add support for 1password new secret reference

### ISSUE THREAD

**Issue by wasdee** [bevry/dorothy#201]
# design
`secret read "op://Personal/hsjdgfsdf/API Key" `
it will return data from `op read --no-newline "op://Personal/hsjdgfsdf/API Key"`

what do you think? im willing to PR this.

**Comment by balupton** [comment]
For that simple action, I think an alias is better.

After the Dorothy campjs talk it was discussed about having secret become multi engine, where 1password is just one of the engines. It's an interesting thought, as some engines could be entirely local - such as a simple read write sudo store.

**Comment by wasdee** [comment]
> For that simple action, I think an alias is better.
> 
> After the Dorothy campjs talk it was discussed about having secret become multi engine, where 1password is just one of the engines. It's an interesting thought, as some engines could be entirely local - such as a simple read write sudo store.

love your idea. admittedly first time i went to the secret i expect it to be multi-engine as well.
