### ISSUE TITLE
Installation errors in supported shell in host shells in Termux and within guest shells within proot-distro aliases in Termux 

### ISSUE THREAD

**Issue by b9Joker108** [bevry/dorothy#214]
To whomever it may concern

On my Samsung Galaxy Tab S9 Ultra, I principally use Zsh augmented with Oh My Zsh! as a general interactive and scripting shell in Termux on Android. I noted that your project doesn't mention Android specifically, but as Android extended with Termux is functionally a *NIX, I considered it would be installable, if with a bit of use-case and environment tweaking. 

```zsh
❯ zsh -l
# To be sure, I invoked Zsh as a login shell
❯ bash -ic "$(curl -fsSL https://dorothy.bevry.me/install)"
# if your shell doesn't recognize any of the above syntax, run `bash -i` then 
# try again, I did this, and in both commands, my shells outputted the 
# following two errors and didn't install
curl: (22) The requested URL returned error: 404
print_line: command not found
```

In my shell, I asked ShellGPT the nature of these errors, and it reponded:

```bash
The error message you're seeing is actually two separate messages:

1 curl: (22) The requested URL returned error: 404 - This indicates that
   curl tried to access a URL, but the server responded with a 404 error,
   which means the requested page could not be found. You should check 
   the  URL for any typos or mistakes, or it might be that the page has been
   moved or deleted.
 2 bash: print_line: command not found - This suggests that you tried to run
   a command called print_line in the bash shell, but bash could not find a
   command with that name. It's possible that you meant to use echo or
   printf to print a line of text, or print_line might be a custom function
   or script that is not in your PATH or is not defined.
```

This information didn't really help me troubleshoot the issue and I followed all instructions on the README.md.

I would really appreciate your assistance in resolving this issue in my host shell environment in Termux. Whilst, I await your response, I am going to try to progress an installation in any of a number of proot-distro alias GNU/Linux distributions I have installed. I first tried on Arch as a proot-distro, but no cigar, now I am going to progress on Kali NetHunter Rootless, Debian, Ubuntu and Parrot.

I am writing a book on shells, scripting and programming, specifically in the Android augmented Termux environment, and came across your project by happenstance and serendipity whilst exploring the traditional and contemporary differences between scripting programming languages and non-scripting programming languages, for inclusion in the work, and to get my head around the topic and its evolution, development and possible futures.

I feel your project has much import for my multi-distribution or operating system, multi-shell use-case, and for my written work in particular. Please refer:

https://github.com/b9Joker108/a.fable.of.the.scriptkiddie.scriptoria/blob/main/A%20Fable%20of%20the%20Scriptkiddie%20Scriptoria%20(GitHub%20test).md

I am still very much a novice and a noob in the shell, and consider for the most part, I will always be, a beginner. Hence, I am writing the work, not only because it needs to be written, but also to teach myself, as I teach others. 

I patiently await your response.
Beauford

P. S.

Tell Benjamin Lupton that we have things in common, apart from multi-environment and multi-shell usage and wanting to facilitate ease of transition between them, I too travelled Australia for a number of years, mostly by hitching and with a number of different swags, my favourite being old-skool canvas. I note, that you perceive things and work differently, and problem-solve differently to most with such experiential leavening. I have become more idealistic, philosophical and profoundly pragmatic as a result, and venture others, such as Lupton, have similarly.

**Comment by balupton** [comment]
Try now

**Comment by balupton** [comment]
Going to close, as assuming that issue is fixed. If you still have issues, please re-open.
