### ISSUE TITLE
Install error command not found on Intel Mac

### ISSUE THREAD

**Issue by jon-agencyspotter** [bevry/dorothy#215]
I'm trying to setup dorothy on an Intel Mac running macOS 14.3.1, but I'm running into the error `echo-segment: command not found` during install.

[dorothy-install.log](https://github.com/bevry/dorothy/files/14422920/dorothy-install.log)

**Comment by balupton** [comment]
From a first look this seems because you have Dorothy installed but not loaded by any dotfiles, as such the assumption the installer has that an existing Dorothy installation should be loaded is incorrect. I'll fix this in a couple of hours.

**Comment by balupton** [comment]
Okay, so I've pushed a fix for this to master. However I believe you are running a fork of Dorothy, so you may need to do the following beforehand and resolve any merge conflicts:

``` bash
cd "$HOME/.local/share/dorothy"
git remote remove bevry || : # remove to ensure we always add the right one
git remote add --fetch bevry 'https://github.com/bevry/dorothy.git'
git pull bevry master 
```

**Comment by balupton** [comment]
Hrmmm. Pity you didn't do the -x trick on that error, I would have been able to fix it. Glad you got it going. Sorry for the inconvenience!
