### ISSUE TITLE
Bug: `sources/ssh.nu` syntax error

### ISSUE THREAD

**Issue by jon-spotsource** [bevry/dorothy#218]
When starting Nushell with dorothy, I get this error:

![image](https://github.com/bevry/dorothy/assets/62892279/39f5dda6-1843-43c5-b48b-3649f147c95d)

The correct syntax for this test is one of these 2:

![image](https://github.com/bevry/dorothy/assets/62892279/d89d783f-8e0a-462a-9bde-ca0e85390cc6)

**Comment by balupton** [comment]
went with not-in, thanks!
