### ISSUE TITLE
Bug: `interactive.sh` is loaded even when `interactive.fish` exists

### ISSUE THREAD

**Issue by edmcman** [bevry/dorothy#222]
From README.md:
> [Fish](https://en.wikipedia.org/wiki/Fish_(Unix_shell)) will load interactive.fish if it exists, otherwise it will load interactive.sh.

This doesn't seem to be the current behavior:

```
hello from interactive.fish
hello from interactive.sh
Thank you to Dorothy contributor 🤍 Sumit Rai 🔗 https://github.com/sumitrai
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
ed@banana ~> 
```

I put echo "hello from X" into $DOROTHY/config/X

This is problematic because I was trying to add some POSIX stuff to `interactive.sh` that fish doesn't like.

**Comment by balupton** [comment]
Will look into it over the next 5 hours.

**Comment by balupton** [comment]
This was an instance where the documentation differed from the implementation. The documentation is the intended behaviour.

I have a fix incoming, just need to implement it for elvish and xonsh as well.

**Comment by edmcman** [comment]
Thanks!
