### ISSUE TITLE
Suggestion: Cross-shell aliases

### ISSUE THREAD

**Issue by edmcman** [bevry/dorothy#226]
Is there a suggested way to add cross-shell aliases?  I use fish, so right now I put them in both `interactive.fish` and `interactive.sh` which is annoying...

**Comment by balupton** [comment]
Many shells, including fish will support sourcing basic POSIX files, ie. I'm a fish shell user, but only have interactive.sh without a interactive.fish:
https://github.com/balupton/dotfiles/blob/master/config/interactive.sh

Try sourcing your interactive.sh file in your interactive.fish file, and if there is say a function or the like inside it which prevents fish compatibility, move the aliases out into an aliases.sh file which is sourced by interactive.sh and interactive.fish

For the long term, perhaps Dorothy could support say a aliases.json file, which then injects the aliases into each shell.

**Comment by edmcman** [comment]
Thanks, I actually looked at your dotfile and didn't realize your aliases were imported to fish.

For now I'll split my aliases into a separate file since I have some stuff in interactive.sh that fish doesn't like.
