### ISSUE TITLE
Bug: crashes in `setup-environment-commands` due to misbehaving ecosystems causes `sources/environment.*` to be empty

### ISSUE THREAD

**Issue by oscarvarto** [bevry/dorothy#235]
I am working on macOS Sonoma 14.5.

I tried doing a *reinstall* of Dorothy after removing `~/.local/share/dorothy` and `~/.config/dorothy`. After running the install command from the README.md:
```
bash -ic "$(curl -fsSL https://dorothy.bevry.me/install)"
```
from my terminal (no matter if I use nu/fish) I get a problem in fish shell. The sourcing of:
```
source '/Users/oscarvarto/.local/share/dorothy/init.fish' # Dorothy
```
is added **at the end of my `config.fish`** and then whenever I open fish, I get a lot of error messages:
```
fish: Unknown command: get-terminal-theme
~/.local/share/dorothy/sources/login.fish (line 37): 
get-terminal-theme --clear-cache
^~~~~~~~~~~~~~~~~^
from sourcing file ~/.local/share/dorothy/sources/login.fish
	called on line 11 of file ~/.local/share/dorothy/init.fish
from sourcing file ~/.local/share/dorothy/init.fish
	called on line 126 of file ~/.config/fish/config.fish
from sourcing file ~/.config/fish/config.fish
	called during startup
fish: Unknown command: command-exists
~/.local/share/dorothy/sources/ssh.fish (line 10): 
if command-exists gpg
   ^~~~~~~~~~~~~^
from sourcing file ~/.local/share/dorothy/sources/ssh.fish
	called on line 12 of file ~/.local/share/dorothy/sources/interactive.fish
from sourcing file ~/.local/share/dorothy/sources/interactive.fish
	called on line 13 of file ~/.local/share/dorothy/init.fish
from sourcing file ~/.local/share/dorothy/init.fish
	called on line 126 of file ~/.config/fish/config.fish
from sourcing file ~/.config/fish/config.fish
	called during startup
fish: Unknown command: command-exists
~/.local/share/dorothy/sources/ssh.fish (line 15): 
if command-exists ssh-agent
   ^~~~~~~~~~~~~^
from sourcing file ~/.local/share/dorothy/sources/ssh.fish
	called on line 12 of file ~/.local/share/dorothy/sources/interactive.fish
from sourcing file ~/.local/share/dorothy/sources/interactive.fish
	called on line 13 of file ~/.local/share/dorothy/init.fish
from sourcing file ~/.local/share/dorothy/init.fish
	called on line 126 of file ~/.config/fish/config.fish
from sourcing file ~/.config/fish/config.fish
	called during startup
fish: Unknown command: command-exists
~/.local/share/dorothy/sources/autocomplete.fish (line 14): 
if test "$AUTOCOMPLETE_TEA" != 'no' && command-exists tea
                                       ^~~~~~~~~~~~~^
from sourcing file ~/.local/share/dorothy/sources/autocomplete.fish
	called on line 13 of file ~/.local/share/dorothy/sources/interactive.fish
from sourcing file ~/.local/share/dorothy/sources/interactive.fish
	called on line 13 of file ~/.local/share/dorothy/init.fish
from sourcing file ~/.local/share/dorothy/init.fish
	called on line 126 of file ~/.config/fish/config.fish
from sourcing file ~/.config/fish/config.fish
	called during startup
fish: Unknown command: command-exists
~/.local/share/dorothy/sources/autocomplete.fish (line 25): 
if command-exists carapace
   ^~~~~~~~~~~~~^
from sourcing file ~/.local/share/dorothy/sources/autocomplete.fish
	called on line 13 of file ~/.local/share/dorothy/sources/interactive.fish
from sourcing file ~/.local/share/dorothy/sources/interactive.fish
	called on line 13 of file ~/.local/share/dorothy/init.fish
from sourcing file ~/.local/share/dorothy/init.fish
	called on line 126 of file ~/.config/fish/config.fish
from sourcing file ~/.config/fish/config.fish
	called during startup
fish: Unknown command: command-exists
~/.local/share/dorothy/sources/interactive.fish (line 16): 
if command-exists shuf
   ^~~~~~~~~~~~~^
from sourcing file ~/.local/share/dorothy/sources/interactive.fish
	called on line 13 of file ~/.local/share/dorothy/init.fish
from sourcing file ~/.local/share/dorothy/init.fish
	called on line 126 of file ~/.config/fish/config.fish
from sourcing file ~/.config/fish/config.fish
	called during startup
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
```

I realized that moving the line:
```
source '/Users/oscarvarto/.local/share/dorothy/init.fish' # Dorothy
```
at the beginning of my `config.fish` gets rid of the error messages, but I think the first time I installed dorothy this wasn't a problem. So, I think I haven't found a way to do a **complete uninstall** of Dorothy to get the things the way they were at the beginning to start over. This is not good 🫤.

**Why there is no easy way to completely uninstall Dorothy and possibly start from scratch?**

===
On the other hand, Dorothy injects a lot of entries to my PATH, which I find very inconvenient, because I loose control of the expected behavior of my programs. E.g. it injected the path to XCode stuff, but then the compilation process for vterm in Emacs (needing a C compiler) failed to find `stdlib.h`. I had to remove the sourcing of Dorothy, make emacs read my original PATH again, and do the compiling process correctly.

**Comment by oscarvarto** [comment]
Now I will try to find the places where dorothy is referenced for several shells in my system and delete them. Maybe they are not in the right place?? Don't know for sure.

**Comment by balupton** [comment]
I'll be home in two hours. If you are available then, I could remote in and find out what is going on.

**Comment by oscarvarto** [comment]
Oh that would be awesome, but it’s almost 4:00 a.m. for me, and I haven’t slept while trying to fix issues (and I will need to work soon). I need to get at least some sleep.
But we can probably do it on a more convenient time for both (please!)
Thanks. I think Dorothy is good. I was using some stuff for ni shell.  
On Thu, Jul 11, 2024 at 3:49 a.m., Benjamin Lupton ***@***.***&gt; wrote:  I'll be home in two hours. If you are available then, I could remote in and find out what is going on.

**Comment by balupton** [comment]
Okay, grab anytime on https://cal.com/balupton/call and we'll arrange a time

**Comment by balupton** [comment]
Join Zoom Meeting
https://us05web.zoom.us/j/9855647764?pwd=Mll2RWc0M3M4NzhnOTdIck5oVHNYZz09

Meeting ID:  985 564 7764
Passcode: liberty53k

**Comment by balupton** [comment]
Actually, zoom just booted me and wants me to wait 6 minutes before starting a new meeting.

**Comment by balupton** [comment]
Okay, back in zoom

**Comment by oscarvarto** [comment]
I had some internet connectivity issues. Like I said in the call, my mother's in law service is bad :(

**Comment by balupton** [comment]
So it was definitely zoom hitting the 40m mark originally, then updating to v6 of the zoom client on my end caused me to have to wait 10 minutes or so before starting a zoom meeting. But now def internet connection issues.

So it was yarn not following standard conventions that caused the `setup-paths-commands` to fail, in which `environment.fish` was not detecting that failure and proceeding as if everything was okay, which it was not.

You can send a PR with those changes `~/.local/share/dorothy` and I'll get them merged, as well as look into better error detection and handling so such failures are not silent.

For where you are at now, you can start moving things from `~/.config/fish/config.fish` that ` ~/.local/share/dorothy/commands/setup-environment-commands` doesn't already handle into an `~/.config/dorothy/config/interactive.fish` file:

- https://github.com/edmcman/dotfiles/blob/main/config/interactive.fish

**Comment by oscarvarto** [comment]
Thanks, @balupton for your help and patience. I'll try to do the MR soon.

**Comment by balupton** [comment]
Merged! Will get to the other tasks over the coming weeks.

**Comment by balupton** [comment]
Note the push fix for this, the detection of the crash and its human readable advice, is only applicable to posix shells and fish. Other shells will need someone experienced with those shells to implement the necessary support in their `environment.*` files
