### ISSUE TITLE
if posix NOT == "sh" then it seems NO interactive.sh files are sourced.

### ISSUE THREAD

**Issue by molleweide** [bevry/dorothy#237]
https://github.com/bevry/dorothy/blob/f416b7f6f60447af965787b10205159ddfe36c6e/sources/interactive.sh#L14

does not seem to load the `sh` files args.

**Comment by balupton** [comment]
if it is .zsh and interactive.zsh exists it will only load interactive.zsh without also loading interactive.sh

this is expected behaviour, if you still want interactive.sh to load under this case, source it in your interactive.zsh

**Comment by molleweide** [comment]
aah perfect. i see now in the git logs from couple months ago
