### ISSUE TITLE
Bug: `config-helper` write mishap with conditional replacements

### ISSUE THREAD

**Issue by molleweide** [bevry/dorothy#241]
In the example below, which is from my setup.bash file, upon auto-rewriting the file, dorothy removed the second instance of `GO_INSTALL` when it attempted to move strong box to setup-util which resulted in only the closing parenthesis being left.

BEFORE:
```bash
if "$DOROTHY/commands/is-mac"; then
	GO_INSTALL=(
		changkun.de/x/rmtrash
		github.com/gennaro-tedesco/boilit # manual install -> `go get -u -v github.com/gennaro-tedesco/boilit`
		github.com/uw-labs/strongbox
		github.com/x-motemen/ghq@latest
		# github.com/cloudflare/utahfs/cmd/utahfs-client
		# https://github.com/maaslalani/nap # cli snippets manager
	)
else
	GO_INSTALL=(
		changkun.de/x/rmtrash
		github.com/gennaro-tedesco/boilit
		github.com/uw-labs/strongbox
		github.com/x-motemen/ghq@latest
		# github.com/rfjakob/gocryptfs: use `setup-util-gocryptfs` instead, as this version lags behind
	)
fi
```

AFTER:

```bash
if "$DOROTHY/commands/is-mac"; then
  GO_INSTALL=(
  	'changkun.de/x/rmtrash'
  	'github.com/gennaro-tedesco/boilit'
  	'github.com/x-motemen/ghq@latest'
  )
else
   ### SYNTAX ERROR HERE... ###
    changkun.de/x/rmtrash
    github.com/gennaro-tedesco/boilit
    github.com/uw-labs/strongbox
    github.com/x-motemen/ghq@latest
    # github.com/rfjakob/gocryptfs: use `setup-util-gocryptfs` instead, as this version lags behind
  )
fi
```

**Comment by balupton** [comment]
Can you provide the before, after, and expected

**Comment by molleweide** [comment]
Yeah, i'll look into the config helper file. i suspected that was the root cause

**Comment by balupton** [comment]
Any news?

**Comment by molleweide** [comment]
I spent a lot of time this week just studying related dorothy commands. Reading up on shit.

If one has a large multi conditional in setup.bash, eg.
```bash
if mac
...
elif wsl
...
elif ubuntu
...
elif linux
...
```
How do we want this to be handled??

There can potentially be a lot of similar looking PKG_INSTALL sections.

-----

Next for me is to just setup up good test cases for this so that i can play around more efficiently.

**Comment by balupton** [comment]
https://github.com/bevry/dorothy/blob/master/docs/scripting/conventions.md#use-if-not-magic

**Comment by molleweide** [comment]
Hmm, i just realized that i dont even know exactly why i had the `is-mac` statement in the first place.
But regardless, having functionality in config-helper that supports basic conditionals still makes sense, I think, right?
Or is it just stupid?

**Comment by balupton** [comment]
I think the bug still needs to be fixed. I think the best option will be to rewrite config-helper from a ripgrep, sd, teip combo into an AWK script instead.

**Comment by molleweide** [comment]
If we do a big rewrite we should/have to consider this
https://ast-grep.github.io/
https://ast-grep.github.io/guide/quick-start.html 
https://ast-grep.github.io/catalog/typescript/#typescript <<< since I know you are an expert in TS.

It allows for making syntax based queries on the code instead of using regex type solutions.

Bash is supported as builtin
https://ast-grep.github.io/reference/languages.html

playground:
https://ast-grep.github.io/playground.html

**Comment by balupton** [comment]
ast-grep seems perfect, however it would then become an essential dorothy dependency and thus constrain which platforms dorothy is available on, furthermore the regexps are already done and a gawk solution, which we already have to make an essential dependency — https://github.com/bevry/dorothy/issues/239 — will still eliminate the need for 3 rust tools (`sd`, `ripgrep`, `teip`).

I will look into ast-grep's platform support, if it does support all our targets (WSL2, amd64, arm64, risc5, apple intel, apple silicon) then will be fine to become an essential dependency, in addition to the gawk essential dep requirement.

**Comment by balupton** [comment]
It doesn't support RISC5 at this point:
- https://github.com/ast-grep/ast-grep/releases/tag/0.26.3
- no issues on their issue tracker about it

**Comment by balupton** [comment]
ast-grep will actually be fine for riscv, as it provides itself via cargo compilation, which is already what we do for all our other rust essential deps.

gawk will not be suitable as a replacement, as we use very advanced regexps which rust regex is suitable for and is what we already use, which gawk does not. However, there is frawk:
https://github.com/ezrosent/frawk

So will go with ast-grep or frawk.

**Comment by balupton** [comment]
Frawk doesn't provide any pre-built binaries:
https://github.com/ezrosent/frawk/issues/53

**Comment by balupton** [comment]
For the OP bug:

before:

``` bash
GO_INSTALL=()
if is-mac; then
	GO_LINTING_INSTALL='yes'
	GO_INSTALL+=(
		'changkun.de/x/rmtrash'
		# 'github.com/cloudflare/utahfs/cmd/utahfs-client'
	)
fi

if "$DOROTHY/commands/is-mac"; then
	GO_INSTALL=(
		changkun.de/x/rmtrash
		github.com/gennaro-tedesco/boilit # manual install -> `go get -u -v github.com/gennaro-tedesco/boilit`
		github.com/uw-labs/strongbox
		github.com/x-motemen/ghq@latest
		# github.com/cloudflare/utahfs/cmd/utahfs-client
		# https://github.com/maaslalani/nap # cli snippets manager
	)
else
	GO_INSTALL=(
		changkun.de/x/rmtrash
		github.com/gennaro-tedesco/boilit
		github.com/uw-labs/strongbox
		github.com/x-motemen/ghq@latest
		# github.com/rfjakob/gocryptfs: use `setup-util-gocryptfs` instead, as this version lags behind
	)
fi
```

after `setup-go`:

``` bash
GO_INSTALL=(
	'changkun.de/x/rmtrash'
	'github.com/gennaro-tedesco/boilit'
	'github.com/x-motemen/ghq@latest'
)
if is-mac; then
	GO_LINTING_INSTALL='yes'
	GO_INSTALL+=(
		'changkun.de/x/rmtrash'
		# 'github.com/cloudflare/utahfs/cmd/utahfs-client'
	)
fi

if "$DOROTHY/commands/is-mac"; then
		changkun.de/x/rmtrash
		github.com/gennaro-tedesco/boilit # manual install -> `go get -u -v github.com/gennaro-tedesco/boilit`
		github.com/uw-labs/strongbox
		github.com/x-motemen/ghq@latest
		# github.com/cloudflare/utahfs/cmd/utahfs-client
		# https://github.com/maaslalani/nap # cli snippets manager
	)
else
		changkun.de/x/rmtrash
		github.com/gennaro-tedesco/boilit
		github.com/uw-labs/strongbox
		github.com/x-motemen/ghq@latest
		# github.com/rfjakob/gocryptfs: use `setup-util-gocryptfs` instead, as this version lags behind
	)
fi
```

**Comment by balupton** [comment]
I will fix this by just fixing the regular expressions in `config-helper`. @molleweide if you want to experiment with `ast-grep` I'll leave that for you.

**Comment by balupton** [comment]
Fixed in dev, but not ideal. Will need to document and communicate the complexity to the user.
