### ISSUE TITLE
Bug: `ask --required ...` causes infinite loop

### ISSUE THREAD

**Issue by balupton** [bevry/dorothy#248]
Since the huge confirm/ask/choose improvements of recent, on my MacBook Pro 2017 there is a regression on `ask --required`. This is causing `setup-system => setup-node => get-profile => ask` to hang. Will debug tomorrow.

**Comment by edmcman** [comment]
I am having trouble installing on a new Mac system.  Probably the same problem?

![image](https://github.com/user-attachments/assets/7dff88af-5441-4ba9-9afb-e37b263659f9)

**Comment by edmcman** [comment]
![image](https://github.com/user-attachments/assets/cfd7f950-dab9-4cb6-a0b6-45044764c01e)

**Comment by balupton** [comment]
@edmcman fixed, run `dorothy update` or `cd $DOROTHY; git pull bevry master` to get the fix.
