### ISSUE TITLE
Better UX around `setup-util-git` SSHFS warning

### ISSUE THREAD

**Issue by molleweide** [bevry/dorothy#59]
```
Error: sshfs has been disabled because it requires closed-source macFUSE!
Error: sshfs not installed
The [SSHFS] utility was unable to be installed. ❌
```

**Comment by balupton** [comment]
Non-fatal. Code indicates it is optional - if dorothy continues, then it is fine. We should do a better job of indicating this to the user.

**Comment by balupton** [comment]
Fixed in https://github.com/bevry/dorothy/commit/0f4feb1d0ea670be4c075d41791eb9226cf19476 which adds a new `OPTIONAL=yes` ability to `setup-util` which `setup-util-git` now uses
