### ISSUE TITLE
macos-intel: goinstall command not found

### ISSUE THREAD

**Issue by molleweide** [bevry/dorothy#66]
i am just documenting what happnes when I run scripts.

```shell
╰ setup-go

Ensuring go is installed...
The [go] utility is already installed because [go] is present. All good. ✅

Reload paths to ensure go is detected...

Installing 1 go packages...
changkun.de/x/rmtrash imports
        flag: package flag is not in GOROOT (/usr/local/Cellar/go/1.16.3/libexec/src/flag)
changkun.de/x/rmtrash imports
        fmt: package fmt is not in GOROOT (/usr/local/Cellar/go/1.16.3/libexec/src/fmt)
changkun.de/x/rmtrash imports
        os: package os is not in GOROOT (/usr/local/Cellar/go/1.16.3/libexec/src/os)
changkun.de/x/rmtrash imports
        os/user: package os/user is not in GOROOT (/usr/local/Cellar/go/1.16.3/libexec/src/os/user)
changkun.de/x/rmtrash imports
        path/filepath: package path/filepath is not in GOROOT (/usr/local/Cellar/go/1.16.3/libexec/src/path/filepath)
changkun.de/x/rmtrash imports
        time: package time is not in GOROOT (/usr/local/Cellar/go/1.16.3/libexec/src/time)
The [go:changkun.de/x/rmtrash] utility was unable to be installed. ❌

Update all go packages? (y/N)
go get: cannot match "all": go.mod file not found in current directory or any parent directory; see 'go help modules'

Install go linting packages? (y/N)
/Users/hjalmarjakobsson/.local/share/dorothy/commands/setup-go: line 61: goinstall: command not found
```

i haven't really used go so I am familiar yet with some of these error messages etc. but I am posting here just so you 
can see what the output is.

**Comment by molleweide** [comment]
```shell
    ╰ go install
    go: cannot find main module, but found .git/config in /Users/hjalmarjakobsson/.local/share/dorothy
            to create a module there, run:
            go mod init

    ╭─     dorothy     molleweide      2  ↵ 1 
    ╰ goinstall
    zsh: command not found: goinstall

    ╭─     dorothy     molleweide      2  ↵ 127 
    ╰
```

**Comment by balupton** [comment]
Did you press `y` to the later two?

**Comment by molleweide** [comment]
I don't think I've had any go things from previously. Only rust stuff but no go.

**Comment by molleweide** [comment]
Yes I pressed yes on all

**Comment by balupton** [comment]
Can you debug this?

**Comment by molleweide** [comment]
Yes ofc i'll try my best

**Comment by balupton** [comment]
```
Installing 2 go packages...
go get: installing executables with 'go get' in module mode is deprecated.
	Use 'go install pkg@version' instead.
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.
The [go:changkun.de/x/rmtrash] utility is now installed via [go]. ✅
go get: installing executables with 'go get' in module mode is deprecated.
	Use 'go install pkg@version' instead.
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.
The [go:github.com/cloudflare/utahfs/cmd/utahfs-client] utility is now installed via [go]. ✅
```

Perhaps our `setup-go` commands have become outdated with the latest go version.

**Comment by balupton** [comment]
> ```shell
> 
> Installing 1 go packages...
> changkun.de/x/rmtrash imports
>         flag: package flag is not in GOROOT (/usr/local/Cellar/go/1.16.3/libexec/src/flag)
> changkun.de/x/rmtrash imports
>         fmt: package fmt is not in GOROOT (/usr/local/Cellar/go/1.16.3/libexec/src/fmt)
> changkun.de/x/rmtrash imports
>         os: package os is not in GOROOT (/usr/local/Cellar/go/1.16.3/libexec/src/os)
> changkun.de/x/rmtrash imports
>         os/user: package os/user is not in GOROOT (/usr/local/Cellar/go/1.16.3/libexec/src/os/user)
> changkun.de/x/rmtrash imports
>         path/filepath: package path/filepath is not in GOROOT (/usr/local/Cellar/go/1.16.3/libexec/src/path/filepath)
> changkun.de/x/rmtrash imports
>         time: package time is not in GOROOT (/usr/local/Cellar/go/1.16.3/libexec/src/time)
> The [go:changkun.de/x/rmtrash] utility was unable to be installed. ❌
> ```

These things could be a XDG conflict with your `environment.bash`, or something else...



> ```shell
> /Users/hjalmarjakobsson/.local/share/dorothy/commands/setup-go: line 61: goinstall: command not found
> ```

this one is my fault, fixing now




> go get: installing executables with 'go get' in module mode is deprecated.
> 	Use 'go install pkg@version' instead.
> 	For more information, see https://golang.org/doc/go-get-install-deprecation
> 	or run 'go help get' or 'go help install'.

I'm looking into this one now

**Comment by molleweide** [comment]
Yeah and i believe that there are more xdg conflicts in other language setups as well. The next one that come to my mind is the ruby installer.

**Comment by molleweide** [comment]
go installers worked for me now.
