### ISSUE TITLE
If a `SETUP_UTILS` item is missing, the error is not helpful.

### ISSUE THREAD

**Issue by molleweide** [bevry/dorothy#67]
when running `setup-utils` for some packages in setup.bash it returns this:
```
/Users/hjalmarjakobsson/.local/share/dorothy/commands/setup-utils: line 12: setup-util-lua: command not found
```
What does this mean. I mean, lua is found on my system so what does this message indicate. I am thinking that I should probably put these commands under brew. But I thought the purpose of `setup-utils` was to install stuff that should go with any package manager available kind of, I'm not hundred sure.

**Comment by balupton** [comment]
So `setup-utils` takes `SETUP_UTILS` array, then iterates through that's array's items, calling the `setup-util-${item}` command. If that command does not exist, then the ability to know how to install it has not yet been figured out.

In your dotfiles repo, you have many `setup-user-*` commands, I believe you are trying to emulate what `setup-utils` and `SETUP_UTILS` are already doing.

We should detect this however, and alert the user to an instruction/documentation on how to code their `user/commands/setup-util-${the missing item}` command.

**Comment by balupton** [comment]
Commit https://github.com/bevry/dorothy/commit/ae0c5ee18bd4cc56fbf1a9ea315fc949ade42720

Now provides clear instructions on what the issue is and how to resolve it.

**Comment by molleweide** [comment]
Its gonna be my pleasure to do this
