### ISSUE TITLE
Better Compatibility: XDG

### ISSUE THREAD

**Issue by molleweide** [bevry/dorothy#69]
unset DOROTHY vars when updating/installing doeo.

Eg. if one moves from non XDG to XDG

**Comment by balupton** [comment]
We need to go over this on a call, as the setup-dorothy command deliberately does not unset them, instead it updates them, and then later on also updates the shell init scripts to reference the correct location.

**Comment by molleweide** [comment]
you probably know how this works better than I do, so let's talk about it next time. I just put it here so we can check it off.

**Comment by balupton** [comment]
Maybe we can rename this to something like `Better XDG compatibility` and focus it on complete XDG support for a XDG user.

**Comment by balupton** [comment]
This was merged with the https://github.com/bevry/dorothy/discussions/94 changes, final commit being: https://github.com/bevry/dorothy/commit/6b9dbb50fedce455ffb3e3aa2b95b21d1069a7c4
