### ISSUE TITLE
`--help` flags for each of the commands

### ISSUE THREAD

**Issue by balupton** [bevry/dorothy#7]
Remaining help text to be applied:

- [ ] `echo-*`
- [ ] `is-*`
- [ ] `eval-no-color` multi args
- [ ] `eval-on-empty-stdin` multi args
- [ ] `eval-on-not-empty-stdin` multi args
- [ ] `expand-path` multi args
- [ ] `expand-path-bash` multi args
- [x] `fs-join` two args
- [x] `fs-volume-join` two args - moved into macos-state where it is used
- [x] `get-arch` no args
- [x] `get-array` single arg
- [x] `get-command` special args
- [x] `get-line-count` zero args, only stdin
- [x] `get-local-to-remote` single arg
- [ ] `openssl-helper` needs help text filled in
- [ ] `setup-*`

Feel free to send PRs

**Comment by balupton** [comment]
Rather than `man` pages for each command, it is best to do `--help` flags for each of them, as it is easier and more robust:

https://github.com/bevry/dorothy/blob/14e619275b9313bf52a99baacce9bf60297ff1a4/commands/cpr#L8-L39

**Comment by balupton** [comment]
For convention, I believe this one is good enough to roll out to the rest:

https://github.com/bevry/dorothy/commit/0d58b427b9a8d8b72d93289355e1fa8dd858b25d

**Comment by balupton** [comment]
@molleweide can I assign this to you?

**Comment by molleweide** [comment]
> @molleweide can I assign this to you?

Yo I'll try to look at this and see what I can do.

**Comment by balupton** [comment]
Would be cool if each command or group of commands also hd a video tutorial, which the help prompt after dumping the usage data, does a confirm prompt if they want to open the video tutorial. It can go on the bevry software channel.

**Comment by balupton** [comment]
Found these.

## https://en.wikipedia.org/wiki/Command-line_interface#Command_description_syntax

> - angle brackets for required parameters: ping <hostname>
> - square brackets for optional parameters: mkdir [-p] <dirname>
> - ellipses for repeated items: cp <source1> [source2…] <dest>
> - vertical bars for choice of items: netstat {-t|-u}

##  https://linux.die.net/man/7/man-pages


> For commands, this shows the syntax of the command and its arguments (including options); boldface is used for as-is text and italics are used to indicate replaceable arguments. Brackets ([]) surround optional arguments, vertical bars (|) separate choices, and ellipses (...) can be repeated. 

Also, it states several sections and what is expected in those sections...

> **The following list elaborates on the contents of each of the above sections.**
> ...

**Comment by balupton** [comment]
Closing in favour of the `dorothy todos` command that was added a while back.
