### ISSUE TITLE
`setup-git` gpg failed to sign 

### ISSUE THREAD

**Issue by molleweide** [bevry/dorothy#70]
Next step for me is also to trouble shoot this. After running setup-git I gets;
```shell
error: gpg failed to sign the data
fatal: failed to write commit object
```
when commiting which means that commiting doesn't work at all.

I could probably go into my user configs and un check this for now.

It was a while ago that I read up on gpg so  I have to refresh my memory on that. I do know however, that I have
a valid master key that exists. I have to walk through the code also to see how you use gpg in dorothy.

**Comment by balupton** [comment]
You're going to have to figure this one out, then report back what changes were necessary.

**Comment by molleweide** [comment]
Yes i will report back later

**Comment by balupton** [comment]
Is this still an issue, or have you figured it out?

**Comment by molleweide** [comment]
No but I haven't had time to look into it much yet. I turned off gpg in my config..

**Comment by balupton** [comment]
Alright, let's close for now, and reopen if it becomes reproduced.
