### ISSUE TITLE
Improvement: have new login shell instances output sponsors, funders, contributors

### ISSUE THREAD

**Issue by balupton** [bevry/dorothy#75]
It would be nice to say thank you to Bevry's sponsors, funders, and contributors.

For sponsors, funders, and contributors, there would be an easy command to run to opt out of this. Otherwise there will be a non-documented ability to opt out.

Ideas for when to display this:

- opening a new terminal, limited to once a day
- upon `setup-dorothy`, limited to once a day

**Comment by molleweide** [comment]
Great idea!

**Comment by molleweide** [comment]
Non documented uglyfied spaghetti code 😃

**Comment by balupton** [comment]
Any suggestions for how it should look?

```
Thank to the Dorothy sponsor Sentry 🗒️ Real-time crash reporting for your web apps, mobile apps, and games 🔗 https://github.com/getsentry
```

**Comment by balupton** [comment]
Went with:

- Thank you to Dorothy sponsor 🤍 Rob Morris 🔗 https://github.com/Rob-Morris
- Thank you to Dorothy sponsor 🤍 Sentry 📝 Real-time crash reporting for your web apps, mobile apps, and games. 🔗 https://github.com/getsentry

This allows shoutouts that are visually appealing, and friendly to terminals, offline, and privacy. As it just outputs a random line from [shoutouts.txt](https://github.com/bevry/dorothy/blob/master/sources/shoutouts.txt).

Later I will have `shoutouts.txt` automatically update, as well as pull in my referral/affiliate links.
