### ISSUE TITLE
What does `Clean NVM installation?` do in `setup-node`?

### ISSUE THREAD

**Issue by molleweide** [bevry/dorothy#81]
I am assuming that `setup-node` is used to install packages from `setup.bash` but if pressing `n` to clean install it seems that some parts related to npm are re-installed if I understand correctly.

**Comment by balupton** [comment]
Need the output.

**Comment by molleweide** [comment]
mm I agree, I'll try to always add the output in future.

**Comment by balupton** [comment]
I've redone this command and am just finishing it up, it will be more clear of what it is doing.

**Comment by molleweide** [comment]
Nice i'll pull this after oon

**Comment by balupton** [comment]
The reworked command is pushed up to:

https://github.com/bevry/dorothy/commit/9f8e6b2a622cc7c66bf095d856ac272416c0d642

Which includes significant improvements to several other commands, notably the `confirm*` commadns
