### ISSUE TITLE
Better Compatibility: XDG: Installing Dorothy

### ISSUE THREAD

**Issue by molleweide** [bevry/dorothy#82]
Yo, 

Just realized I don't know how to pass the XDG flag to the in `curl` command on a new computer.
I note it here but maybe this is an easy thing to solve.

**Comment by balupton** [comment]
Need more context.

**Comment by molleweide** [comment]
basically how would one pass xdg to this:
```
bash -ilc "$(curl -fsSL https://raw.githubusercontent.com/bevry/dorothy/master/commands/setup-dorothy)"
```

**Comment by molleweide** [comment]
some other issues have also occured whilst installing on my M1. I am going to document it and post in another issue later.

**Comment by balupton** [comment]
```
env DOROTHY_XDG=yes bash -ilc "$(curl -fsSL https://raw.githubusercontent.com/bevry/dorothy/master/commands/setup-dorothy)"
```

should work, or

```
bash -ilc "export DOROTHY_XDG=yes; $(curl -fsSL https://raw.githubusercontent.com/bevry/dorothy/master/commands/setup-dorothy)"
```

**Comment by molleweide** [comment]
Aah allright, i sidn't know what terminology to use.

**Comment by balupton** [comment]
So here's what I'm thinking.

setup-dorothy will prompt if you want to use xdg if dorothy has not yet been cloned out.

if dorothy has been cloned out, then we check if dorothy is located in the xdg location, if we are then we set DOROTHY_XDG to yes

If dorothy has been cloned out, and we are in setup-dorothy install mode, then we ask if they want to use xdg or not.

In setup-environment-commands we do the same source location check to autoset DOROTHY_XDG to the correct value, and if we are in DOROTHY_XDG mode then that script actively moves everything to the xdg locations and exports the xdg locations.

if we are not in xdg locations, then we check if the xdg location exists, check if the non xdg location exists, and if both exist then we show a prompt to remove one of the offenders.

**Comment by molleweide** [comment]
oooh what' dorothy edit?

okay so I conclude you don't think the user should have an XDG bool in their environment.bash or similar, ie. XDG is only based on what dirs exist and their locations. and one specifies these locations in `dorothy setup`. I am just rephrasing to make sure I follow. Because I want to be super sure I am following you before I go off doing stupid shit haha. 

1. `dorothy setup` prompts for XDG yes/no.
2. environmnet paths are being set based on this, ie. home/dorothy -> NO XDG || config/dorothy -> YES XDG.

we don't explicitly set environmnet variable `DOROTHY_XDG`. Are there downsides with this I am not aware of?

**Comment by balupton** [comment]
I'm tackling the setup changes now, will leave the `setup-environment-commands` stuff for you

**Comment by molleweide** [comment]
Perfect

**Comment by balupton** [comment]
Completed via #105 and #94
