### ISSUE TITLE
Create new `dorothy` command

### ISSUE THREAD

**Issue by balupton** [bevry/dorothy#93]
Task to track the following changes:

- [x] create `commands/dorothy`
- [x] `setup-dorothy` -> `dorothy setup`, `dorothy install`, `dorothy update`, `dorothy trial`
- [x] `setup-dorothy-permissions` -> `dorothy perms`
- [x] `edit-dorothy` -> `dorothy edit`, `dorothy review`
- [x] `select-theme` -> `dorothy theme`
- [x] `dorothy trial [shell=zsh|bash|fish]` will create an interactive trial subshell

Other ecosystem tasks:

- [x] ensure the trial mode cloudflare worker is updated to reflect the move
- [x] ensure the install instructions is updated to reflect the move

**Comment by molleweide** [comment]
ooh cool with the theme!!!

**Comment by balupton** [comment]
This has been merged.

Changelog:

https://github.com/bevry/dorothy/compare/90745ea19856199e9a300e07b3212df4b74a0238...2a705286daad5a42b36b9a0ccb7b30486787aac1
