### ISSUE TITLE
Better Compatibility: Alpine Linux

### ISSUE THREAD

**Issue by balupton** [bevry/dorothy#96]
Notably:

- [x] update our `setup-dns` to use [apline's `setup-dns`](https://wiki.alpinelinux.org/wiki/Alpine_setup_scripts#setup-dns) which is located at `/sbin/setup-dns` and thus is only available to sudo
- [x] make sure that `setup-install` and `setup-update` run to completion

**Comment by molleweide** [comment]
Never heard of alpine b4

**Comment by balupton** [comment]
It's very popular as the base image for containers, however apparently it can even scale to desktops. Seems a preconfigured arch alternative. Considering giving it a go on a raspberry pi 4 server.

**Comment by molleweide** [comment]
Cool!!

**Comment by balupton** [comment]
This is done, only issue is that alpine uses ash, so to enter Dorothy one must run  `bash -il`
