### ISSUE TITLE
Bug: rewrite `choose-menu` such that it can handle more than `$LINES`

### ISSUE THREAD

**Issue by balupton** [bevry/dorothy#97]
Currently if there are more items than `$LINES` only the last parts will show, then everything will be more or less busted.

**Comment by balupton** [comment]
This will be pretty difficult, but will be another leap in UX, from good to great.

**Comment by molleweide** [comment]
Ooh cool! This is gonna be so nice to follow.

**Comment by balupton** [comment]
I'm thinking until Dorothy becomes more popular (becomes funded), this should suffice for more use cases:

```
if output >= $LINES (with an offset consideration too); then
    resize terminal to the max
    repeat check, if still fails, then fail with a link to this issue
```

**Comment by balupton** [comment]
One alternative to this would be to fallback to charm's gum.

**Comment by balupton** [comment]
https://github.com/charmbracelet/gum has the same issue

**Comment by balupton** [comment]
Can use:

``` bash
# https://www.gnu.org/software/coreutils/manual/html_node/fmt-invocation.html
fmt --width=$COLUMNS <<< ...
fmt $COLUMNS <<< ...

# https://www.gnu.org/software/coreutils/manual/html_node/fold-invocation.html
fold -w $COLUMNS <<< ... # doesn't work well
```

**Comment by balupton** [comment]
Using the formatting coreutils, I was able to accomplish this in about 4 hours. The difficulty was more in the required optimisations to keep it performant to not have flickers on each update, as well as how to handle paging in a way that makes sense with the constraints of the algorithm.

It's pushed to dev, and I'll test it over the day.

**Comment by balupton** [comment]
This is now merged to master. Took another 4 hours today to rewrite for performance, and refine the interactions. Woohoo on solving the last known bug in Dorothy.
